# Generated by Django 4.1.7 on 2023-03-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('UavId', models.AutoField(primary_key=True, serialize=False)),
                ('UavName', models.CharField(max_length=500)),
                ('UavModel', models.CharField(max_length=500)),
                ('UavWeight', models.PositiveIntegerField()),
                ('UavCategory', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('UserPassword', models.CharField(max_length=500)),
            ],
        ),
    ]
