# Generated by Django 4.1.7 on 2023-03-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='UserMail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
